### ISSUE TITLE
Broken on Board Page

### ISSUE THREAD

**Issue by mhaseeb-seecs** [erichk4/kanboard-theme-material-like#2]
I changed the config file according to the theme. 
like the following code.
```
$themePlusConfig['theme'] = 'default';
// $themePlusConfig['css'] = 'material.css';
// $themePlusConfig['login-logo'] = 'kanboard_logo.png';
// $themePlusConfig['logo'] = 'kanboard_logo.png';
// $themePlusConfig['favicon'] = 'favicon.png';
```
if i uncomment these 4 lines the Board Page doesn't show up. All Files are present in respective folders.  Style Loads as well as the logo.

**Comment by Voxay** [comment]
By looking at the source code, I found where the problem came from.
The problem comes from kanboard-themeplus which contains a method that no longer exists. 
# Someone has found a solution to this: https://github.com/phsteffen/kanboard-themeplus/issues/14
